# nb-model_template

In [4]:
import sys
import os
from os import sep
from os.path import dirname, realpath
from pathlib import Path
from functools import partial, reduce
import logging

def get_cwd(fname, subdir, crunch_dir=realpath(Path.home()) +sep +'crunch' +sep):
    """
    Convenience function to make a directory string for the current file based on inputs.
    Jupyter Notebook in Anaconda invokes the Python interpreter in Anaconda's subdirectory
    which is why changing sys.argv[0] is necessary. In the future a better way to do this
    should be preferred..
    """
    return crunch_dir +subdir +fname

def fix_path(cwd):
    """
    Convenience function to fix argv and python path so that jupyter notebook can run the same as
    any script in crunch.
    """
    sys.argv[0] = cwd
    module_path = os.path.abspath(os.path.join('..'))
    if module_path not in sys.path:
        sys.path.append(module_path)

fname = 'nb-model_template.ipynb'   # FILL
dir_name = 'model'                  # FILL
fix_path(get_cwd(fname, dir_name +sep))

import numpy as np
import pandas as pd
#import matplotlib.pyplot as plt
from dask import delayed, compute
from torch.utils.data import TensorDataset, DataLoader
import torch

from ipywidgets import interact, interactive, fixed
from IPython.display import display

pd.set_option("display.max_rows", 100)
pd.set_option('display.max_columns', 50)

from common_util import RECON_DIR, JSON_SFX_LEN, DT_CAL_DAILY_FREQ, is_type, pd_common_idx_rows, remove_dups_list, set_loglevel, search_df, chained_filter, get_variants, dump_df, load_json, gb_transpose, pd_common_index_rows, filter_cols_below, inner_join, outer_join, ser_shift, list_get_dict, window_iter, benchmark
from common_util import midx_get_level, midx_intersect, pd_common_idx_rows, midx_split, pd_midx_to_arr, window_iter, np_is_ndim
from model.common import DATASET_DIR, XG_DIR, EXPECTED_NUM_HOURS, default_dataset
from model.dataprep_util import align_first_last_cols, prune_nulls
from model.datagen_util import xgdg
from data.data_api import DataAPI
from recon.dataset_util import prep_dataset, gen_group
#from recon.split_util import get_train_test_split, gen_time_series_split, index_three_split, pd_binary_clip
DataAPI.__init__()
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

CRITICAL:root:script location: /home/kev/crunch/model/nb-model_template.ipynb
CRITICAL:root:using project dir: /home/kev/crunch/
Using TensorFlow backend.
W0916 19:17:28.712528 139779581159232 deprecation_wrapper.py:119] From /home/kev/crunch/model/common.py:19: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

W0916 19:17:28.713118 139779581159232 deprecation_wrapper.py:119] From /home/kev/crunch/model/common.py:19: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.



## Util functions:

In [10]:
def debug_xg(xg_fname, assets=None):
    """
    Display processed data of an experiment group.
    """
    for i, (paths, recs, dfs) in enumerate(xgdg(xg_fname, delayed=True, assets=assets, filters_map=None)):
        fpath, lpath, tpath = paths
        frec, lrec, trec = recs
        logging.info('(X, y, z) -> ({fdesc}[:], {ldesc}[:], {tdesc}[:])'.format(fdesc=frec.desc, ldesc=lrec.desc, tdesc=trec.desc))
        with benchmark('time to load data') as b:
            f, l, t = dfs.compute()

        val_ratio = .2
        test_ratio = .2
        train_ratio = 1-(val_ratio+test_ratio)
        f_train_idx, f_val_idx, f_test_idx = midx_split(f.index, train_ratio, val_ratio, test_ratio)
        l_train_idx, l_val_idx, l_test_idx = midx_split(l.index, train_ratio, val_ratio, test_ratio)
        t_train_idx, t_val_idx, t_test_idx = midx_split(t.index, train_ratio, val_ratio, test_ratio)

        f_train_pd, f_val_pd, f_test_pd = f.loc[f_train_idx], f.loc[f_val_idx], f.loc[f_test_idx]
        l_train_pd, l_val_pd, l_test_pd = l.loc[l_train_idx], l.loc[l_val_idx], l.loc[l_test_idx]
        t_train_pd, t_val_pd, t_test_pd = t.loc[t_train_idx], t.loc[t_val_idx], t.loc[t_test_idx]

        if (is_type(f.index, pd.core.index.MultiIndex)):
            f_train_np, f_val_np, f_test_np = map(pd_midx_to_arr, [f_train_pd.stack(), f_val_pd.stack(), f_test_pd.stack()])
        else:
            f_train_np, f_val_np, f_test_np = f_train_pd.values, f_val_pd.values, f_test_pd.values
        l_train_np, l_val_np, l_test_np = l_train_pd.values, l_val_pd.values, l_test_pd.values
        t_train_np, t_val_np, t_test_np = t_train_pd.values, t_val_pd.values, t_test_pd.values
        
        display (i)
        display('f.shape: {}, l.shape:{}, t.shape:{}'.format(f_train_np.shape, l_train_np.shape, t_train_np.shape))
        display('f:', f_train_np)

In [11]:
debug_xg('xg0.json', assets='sp_500')

/home/kev/miniconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py:708: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels = getattr(columns, 'labels', None) or [
/home/kev/miniconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py:735: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return pd.MultiIndex(levels=new_levels, labels=labels, names=columns.names)
/home/kev/miniconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py:752: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels, = index.labels
E0916 20:00:23.870556 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


0

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 902.99     ,  934.73     ,  899.35     ,  931.8      ,
         919.8747875],
       [ 929.17     ,  936.63     ,  919.53     ,  927.45     ,
         928.0481125],
       [ 931.17     ,  943.85     ,  927.28     ,  934.7      ,
         934.7745   ],
       ...,
       [1888.19     , 1896.33     , 1885.39     , 1892.49     ,
        1893.2469375],
       [1893.32     , 1901.26     , 1893.32     , 1900.53     ,
        1898.6895125],
       [1902.01     , 1912.28     , 1902.01     , 1911.91     ,
        1909.92945  ]])

E0916 20:00:23.909759 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


1

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 902.99     ,  934.73     ,  899.35     ,  931.8      ,
         919.8747875],
       [ 929.17     ,  936.63     ,  919.53     ,  927.45     ,
         928.0481125],
       [ 931.17     ,  943.85     ,  927.28     ,  934.7      ,
         934.7745   ],
       ...,
       [1888.19     , 1896.33     , 1885.39     , 1892.49     ,
        1893.2469375],
       [1893.32     , 1901.26     , 1893.32     , 1900.53     ,
        1898.6895125],
       [1902.01     , 1912.28     , 1902.01     , 1911.91     ,
        1909.92945  ]])

E0916 20:00:23.945448 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


2

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 902.99     ,  934.73     ,  899.35     ,  931.8      ,
         919.8747875],
       [ 929.17     ,  936.63     ,  919.53     ,  927.45     ,
         928.0481125],
       [ 931.17     ,  943.85     ,  927.28     ,  934.7      ,
         934.7745   ],
       ...,
       [1888.19     , 1896.33     , 1885.39     , 1892.49     ,
        1893.2469375],
       [1893.32     , 1901.26     , 1893.32     , 1900.53     ,
        1898.6895125],
       [1902.01     , 1912.28     , 1902.01     , 1911.91     ,
        1909.92945  ]])

E0916 20:00:23.987150 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


3

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 902.99     ,  934.73     ,  899.35     ,  931.8      ,
         919.8747875],
       [ 929.17     ,  936.63     ,  919.53     ,  927.45     ,
         928.0481125],
       [ 931.17     ,  943.85     ,  927.28     ,  934.7      ,
         934.7745   ],
       ...,
       [1888.19     , 1896.33     , 1885.39     , 1892.49     ,
        1893.2469375],
       [1893.32     , 1901.26     , 1893.32     , 1900.53     ,
        1898.6895125],
       [1902.01     , 1912.28     , 1902.01     , 1911.91     ,
        1909.92945  ]])

E0916 20:00:24.024776 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


4

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[39.58     , 39.82     , 36.88     , 39.19     , 38.054225 ],
       [39.24     , 40.22     , 38.3      , 39.08     , 39.116175 ],
       [38.06     , 39.33     , 37.34     , 38.56     , 38.4035875],
       ...,
       [11.93     , 12.09     , 11.68     , 12.03     , 11.844175 ],
       [11.96     , 11.97     , 11.36     , 11.36     , 11.5871   ],
       [11.69     , 11.84     , 11.5      , 11.51     , 11.627125 ]])

E0916 20:00:24.064764 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


5

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[39.58     , 39.82     , 36.88     , 39.19     , 38.054225 ],
       [39.24     , 40.22     , 38.3      , 39.08     , 39.116175 ],
       [38.06     , 39.33     , 37.34     , 38.56     , 38.4035875],
       ...,
       [11.93     , 12.09     , 11.68     , 12.03     , 11.844175 ],
       [11.96     , 11.97     , 11.36     , 11.36     , 11.5871   ],
       [11.69     , 11.84     , 11.5      , 11.51     , 11.627125 ]])

E0916 20:00:24.103831 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


6

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[39.58     , 39.82     , 36.88     , 39.19     , 38.054225 ],
       [39.24     , 40.22     , 38.3      , 39.08     , 39.116175 ],
       [38.06     , 39.33     , 37.34     , 38.56     , 38.4035875],
       ...,
       [11.93     , 12.09     , 11.68     , 12.03     , 11.844175 ],
       [11.96     , 11.97     , 11.36     , 11.36     , 11.5871   ],
       [11.69     , 11.84     , 11.5      , 11.51     , 11.627125 ]])

E0916 20:00:24.138414 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


7

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[39.58     , 39.82     , 36.88     , 39.19     , 38.054225 ],
       [39.24     , 40.22     , 38.3      , 39.08     , 39.116175 ],
       [38.06     , 39.33     , 37.34     , 38.56     , 38.4035875],
       ...,
       [11.93     , 12.09     , 11.68     , 12.03     , 11.844175 ],
       [11.96     , 11.97     , 11.36     , 11.36     , 11.5871   ],
       [11.69     , 11.84     , 11.5      , 11.51     , 11.627125 ]])

E0916 20:00:24.169864 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


8

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 36828.7       ,  63420.7       ,  36828.7       ,
         63420.7       ,  48454.16666667],
       [ 31826.4       ,  96613.6       ,  31826.4       ,
         96613.6       ,  64301.03333333],
       [130119.6       , 130119.6       , 123524.2       ,
        126852.6       , 126132.86666667],
       ...,
       [270887.1       , 270887.1       , 251627.6       ,
        255129.8       , 258412.1       ],
       [236790.9       , 236790.9       , 194949.        ,
        194949.        , 218447.32222222],
       [109138.8       , 192726.2       , 109138.8       ,
        192726.2       , 154209.02222222]])

E0916 20:00:24.202757 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


9

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 36828.7       ,  63420.7       ,  36828.7       ,
         63420.7       ,  48454.16666667],
       [ 31826.4       ,  96613.6       ,  31826.4       ,
         96613.6       ,  64301.03333333],
       [130119.6       , 130119.6       , 123524.2       ,
        126852.6       , 126132.86666667],
       ...,
       [270887.1       , 270887.1       , 251627.6       ,
        255129.8       , 258412.1       ],
       [236790.9       , 236790.9       , 194949.        ,
        194949.        , 218447.32222222],
       [109138.8       , 192726.2       , 109138.8       ,
        192726.2       , 154209.02222222]])

E0916 20:00:24.238744 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


10

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 36828.7       ,  63420.7       ,  36828.7       ,
         63420.7       ,  48454.16666667],
       [ 31826.4       ,  96613.6       ,  31826.4       ,
         96613.6       ,  64301.03333333],
       [130119.6       , 130119.6       , 123524.2       ,
        126852.6       , 126132.86666667],
       ...,
       [270887.1       , 270887.1       , 251627.6       ,
        255129.8       , 258412.1       ],
       [236790.9       , 236790.9       , 194949.        ,
        194949.        , 218447.32222222],
       [109138.8       , 192726.2       , 109138.8       ,
        192726.2       , 154209.02222222]])

E0916 20:00:24.274346 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


11

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 36828.7       ,  63420.7       ,  36828.7       ,
         63420.7       ,  48454.16666667],
       [ 31826.4       ,  96613.6       ,  31826.4       ,
         96613.6       ,  64301.03333333],
       [130119.6       , 130119.6       , 123524.2       ,
        126852.6       , 126132.86666667],
       ...,
       [270887.1       , 270887.1       , 251627.6       ,
        255129.8       , 258412.1       ],
       [236790.9       , 236790.9       , 194949.        ,
        194949.        , 218447.32222222],
       [109138.8       , 192726.2       , 109138.8       ,
        192726.2       , 154209.02222222]])

E0916 20:00:24.307050 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


12

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[1643.9       , 3888.1       , 1643.9       , 3888.1       ,
        2763.44444444],
       [1890.9       , 4532.8       , 1890.9       , 4532.8       ,
        3028.6       ],
       [6733.        , 7128.        , 6612.4       , 6739.6       ,
        6803.13333333],
       ...,
       [5922.2       , 6829.8       , 5922.2       , 6829.8       ,
        6365.9       ],
       [6382.9       , 6382.9       , 5045.4       , 5045.4       ,
        5899.55555556],
       [1241.5       , 3331.        , 1241.5       , 3331.        ,
        2236.34444444]])

E0916 20:00:24.340414 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


13

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[1643.9       , 3888.1       , 1643.9       , 3888.1       ,
        2763.44444444],
       [1890.9       , 4532.8       , 1890.9       , 4532.8       ,
        3028.6       ],
       [6733.        , 7128.        , 6612.4       , 6739.6       ,
        6803.13333333],
       ...,
       [5922.2       , 6829.8       , 5922.2       , 6829.8       ,
        6365.9       ],
       [6382.9       , 6382.9       , 5045.4       , 5045.4       ,
        5899.55555556],
       [1241.5       , 3331.        , 1241.5       , 3331.        ,
        2236.34444444]])

E0916 20:00:24.373430 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


14

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[1643.9       , 3888.1       , 1643.9       , 3888.1       ,
        2763.44444444],
       [1890.9       , 4532.8       , 1890.9       , 4532.8       ,
        3028.6       ],
       [6733.        , 7128.        , 6612.4       , 6739.6       ,
        6803.13333333],
       ...,
       [5922.2       , 6829.8       , 5922.2       , 6829.8       ,
        6365.9       ],
       [6382.9       , 6382.9       , 5045.4       , 5045.4       ,
        5899.55555556],
       [1241.5       , 3331.        , 1241.5       , 3331.        ,
        2236.34444444]])

E0916 20:00:24.406672 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


15

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[1643.9       , 3888.1       , 1643.9       , 3888.1       ,
        2763.44444444],
       [1890.9       , 4532.8       , 1890.9       , 4532.8       ,
        3028.6       ],
       [6733.        , 7128.        , 6612.4       , 6739.6       ,
        6803.13333333],
       ...,
       [5922.2       , 6829.8       , 5922.2       , 6829.8       ,
        6365.9       ],
       [6382.9       , 6382.9       , 5045.4       , 5045.4       ,
        5899.55555556],
       [1241.5       , 3331.        , 1241.5       , 3331.        ,
        2236.34444444]])

E0916 20:00:24.438761 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


16

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[  753.5       ,  1438.5       ,   753.5       ,  1438.5       ,
         1086.27777778],
       [ 1831.        ,  3118.5       ,  1831.        ,  3118.5       ,
         2563.05555556],
       [ 2873.5       ,  3127.5       ,  2532.        ,  3127.5       ,
         2804.27777778],
       ...,
       [10536.        , 10536.        ,  6644.5       ,  6644.5       ,
         8859.94444444],
       [ 3355.5       ,  3355.5       ,  2535.5       ,  2535.5       ,
         3064.61111111],
       [  908.5       ,  1653.        ,   908.5       ,  1653.        ,
         1228.        ]])

E0916 20:00:24.481171 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


17

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[  753.5       ,  1438.5       ,   753.5       ,  1438.5       ,
         1086.27777778],
       [ 1831.        ,  3118.5       ,  1831.        ,  3118.5       ,
         2563.05555556],
       [ 2873.5       ,  3127.5       ,  2532.        ,  3127.5       ,
         2804.27777778],
       ...,
       [10536.        , 10536.        ,  6644.5       ,  6644.5       ,
         8859.94444444],
       [ 3355.5       ,  3355.5       ,  2535.5       ,  2535.5       ,
         3064.61111111],
       [  908.5       ,  1653.        ,   908.5       ,  1653.        ,
         1228.        ]])

E0916 20:00:24.525109 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


18

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[  753.5       ,  1438.5       ,   753.5       ,  1438.5       ,
         1086.27777778],
       [ 1831.        ,  3118.5       ,  1831.        ,  3118.5       ,
         2563.05555556],
       [ 2873.5       ,  3127.5       ,  2532.        ,  3127.5       ,
         2804.27777778],
       ...,
       [10536.        , 10536.        ,  6644.5       ,  6644.5       ,
         8859.94444444],
       [ 3355.5       ,  3355.5       ,  2535.5       ,  2535.5       ,
         3064.61111111],
       [  908.5       ,  1653.        ,   908.5       ,  1653.        ,
         1228.        ]])

E0916 20:00:24.570456 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


19

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[  753.5       ,  1438.5       ,   753.5       ,  1438.5       ,
         1086.27777778],
       [ 1831.        ,  3118.5       ,  1831.        ,  3118.5       ,
         2563.05555556],
       [ 2873.5       ,  3127.5       ,  2532.        ,  3127.5       ,
         2804.27777778],
       ...,
       [10536.        , 10536.        ,  6644.5       ,  6644.5       ,
         8859.94444444],
       [ 3355.5       ,  3355.5       ,  2535.5       ,  2535.5       ,
         3064.61111111],
       [  908.5       ,  1653.        ,   908.5       ,  1653.        ,
         1228.        ]])

E0916 20:00:24.615042 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


20

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[2868.4       , 7877.        , 2868.4       , 7877.        ,
        5152.74444444],
       [4000.7       , 8370.9       , 4000.7       , 8370.9       ,
        6031.42222222],
       [8320.6       , 8320.6       , 6878.3       , 6878.3       ,
        7633.57777778],
       ...,
       [7282.1       , 7640.8       , 7282.1       , 7397.        ,
        7473.8       ],
       [6806.6       , 6876.9       , 6278.1       , 6365.2       ,
        6618.37777778],
       [1515.6       , 5083.5       , 1515.6       , 5083.5       ,
        3331.84444444]])

E0916 20:00:24.655169 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


21

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[2868.4       , 7877.        , 2868.4       , 7877.        ,
        5152.74444444],
       [4000.7       , 8370.9       , 4000.7       , 8370.9       ,
        6031.42222222],
       [8320.6       , 8320.6       , 6878.3       , 6878.3       ,
        7633.57777778],
       ...,
       [7282.1       , 7640.8       , 7282.1       , 7397.        ,
        7473.8       ],
       [6806.6       , 6876.9       , 6278.1       , 6365.2       ,
        6618.37777778],
       [1515.6       , 5083.5       , 1515.6       , 5083.5       ,
        3331.84444444]])

E0916 20:00:24.689778 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


22

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[2868.4       , 7877.        , 2868.4       , 7877.        ,
        5152.74444444],
       [4000.7       , 8370.9       , 4000.7       , 8370.9       ,
        6031.42222222],
       [8320.6       , 8320.6       , 6878.3       , 6878.3       ,
        7633.57777778],
       ...,
       [7282.1       , 7640.8       , 7282.1       , 7397.        ,
        7473.8       ],
       [6806.6       , 6876.9       , 6278.1       , 6365.2       ,
        6618.37777778],
       [1515.6       , 5083.5       , 1515.6       , 5083.5       ,
        3331.84444444]])

E0916 20:00:24.723070 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


23

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[2868.4       , 7877.        , 2868.4       , 7877.        ,
        5152.74444444],
       [4000.7       , 8370.9       , 4000.7       , 8370.9       ,
        6031.42222222],
       [8320.6       , 8320.6       , 6878.3       , 6878.3       ,
        7633.57777778],
       ...,
       [7282.1       , 7640.8       , 7282.1       , 7397.        ,
        7473.8       ],
       [6806.6       , 6876.9       , 6278.1       , 6365.2       ,
        6618.37777778],
       [1515.6       , 5083.5       , 1515.6       , 5083.5       ,
        3331.84444444]])

E0916 20:00:24.808615 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


24

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 37199.8       ,  68609.9       ,  37199.8       ,
         68609.9       ,  51299.16666667],
       [ 52081.5       ,  70766.8       ,  52081.5       ,
         70766.8       ,  61893.22222222],
       [ 65532.1       ,  72883.6       ,  65531.5       ,
         72883.6       ,  68597.01111111],
       ...,
       [137805.6       , 138244.5       , 133221.2       ,
        138244.5       , 136185.4       ],
       [131591.6       , 131591.6       , 114123.5       ,
        114123.5       , 122806.07777778],
       [ 56714.3       , 106264.6       ,  56714.3       ,
        106264.6       ,  80202.81111111]])

E0916 20:00:24.841027 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


25

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 37199.8       ,  68609.9       ,  37199.8       ,
         68609.9       ,  51299.16666667],
       [ 52081.5       ,  70766.8       ,  52081.5       ,
         70766.8       ,  61893.22222222],
       [ 65532.1       ,  72883.6       ,  65531.5       ,
         72883.6       ,  68597.01111111],
       ...,
       [137805.6       , 138244.5       , 133221.2       ,
        138244.5       , 136185.4       ],
       [131591.6       , 131591.6       , 114123.5       ,
        114123.5       , 122806.07777778],
       [ 56714.3       , 106264.6       ,  56714.3       ,
        106264.6       ,  80202.81111111]])

E0916 20:00:24.873808 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


26

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 37199.8       ,  68609.9       ,  37199.8       ,
         68609.9       ,  51299.16666667],
       [ 52081.5       ,  70766.8       ,  52081.5       ,
         70766.8       ,  61893.22222222],
       [ 65532.1       ,  72883.6       ,  65531.5       ,
         72883.6       ,  68597.01111111],
       ...,
       [137805.6       , 138244.5       , 133221.2       ,
        138244.5       , 136185.4       ],
       [131591.6       , 131591.6       , 114123.5       ,
        114123.5       , 122806.07777778],
       [ 56714.3       , 106264.6       ,  56714.3       ,
        106264.6       ,  80202.81111111]])

E0916 20:00:24.905594 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


27

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 37199.8       ,  68609.9       ,  37199.8       ,
         68609.9       ,  51299.16666667],
       [ 52081.5       ,  70766.8       ,  52081.5       ,
         70766.8       ,  61893.22222222],
       [ 65532.1       ,  72883.6       ,  65531.5       ,
         72883.6       ,  68597.01111111],
       ...,
       [137805.6       , 138244.5       , 133221.2       ,
        138244.5       , 136185.4       ],
       [131591.6       , 131591.6       , 114123.5       ,
        114123.5       , 122806.07777778],
       [ 56714.3       , 106264.6       ,  56714.3       ,
        106264.6       ,  80202.81111111]])

E0916 20:00:24.939907 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


28

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 300.2       ,  353.7       ,  288.2       ,  353.7       ,
         312.25555556],
       [ 340.5       ,  760.5       ,  340.5       ,  760.5       ,
         550.        ],
       [ 820.5       ,  820.5       ,  555.7       ,  555.7       ,
         689.58888889],
       ...,
       [1147.5       , 1427.2       , 1142.3       , 1291.2       ,
        1267.46666667],
       [1470.8       , 1470.8       , 1102.6       , 1183.3       ,
        1263.5       ],
       [ 691.4       ,  899.8       ,  691.4       ,  899.8       ,
         833.72222222]])

E0916 20:00:24.972163 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


29

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 300.2       ,  353.7       ,  288.2       ,  353.7       ,
         312.25555556],
       [ 340.5       ,  760.5       ,  340.5       ,  760.5       ,
         550.        ],
       [ 820.5       ,  820.5       ,  555.7       ,  555.7       ,
         689.58888889],
       ...,
       [1147.5       , 1427.2       , 1142.3       , 1291.2       ,
        1267.46666667],
       [1470.8       , 1470.8       , 1102.6       , 1183.3       ,
        1263.5       ],
       [ 691.4       ,  899.8       ,  691.4       ,  899.8       ,
         833.72222222]])

E0916 20:00:25.004990 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


30

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 300.2       ,  353.7       ,  288.2       ,  353.7       ,
         312.25555556],
       [ 340.5       ,  760.5       ,  340.5       ,  760.5       ,
         550.        ],
       [ 820.5       ,  820.5       ,  555.7       ,  555.7       ,
         689.58888889],
       ...,
       [1147.5       , 1427.2       , 1142.3       , 1291.2       ,
        1267.46666667],
       [1470.8       , 1470.8       , 1102.6       , 1183.3       ,
        1263.5       ],
       [ 691.4       ,  899.8       ,  691.4       ,  899.8       ,
         833.72222222]])

E0916 20:00:25.038588 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


31

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 300.2       ,  353.7       ,  288.2       ,  353.7       ,
         312.25555556],
       [ 340.5       ,  760.5       ,  340.5       ,  760.5       ,
         550.        ],
       [ 820.5       ,  820.5       ,  555.7       ,  555.7       ,
         689.58888889],
       ...,
       [1147.5       , 1427.2       , 1142.3       , 1291.2       ,
        1267.46666667],
       [1470.8       , 1470.8       , 1102.6       , 1183.3       ,
        1263.5       ],
       [ 691.4       ,  899.8       ,  691.4       ,  899.8       ,
         833.72222222]])

E0916 20:00:25.071712 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


32

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 225.5       ,  294.        ,  219.5       ,  294.        ,
         244.88888889],
       [ 393.5       ,  535.5       ,  393.5       ,  535.5       ,
         475.88888889],
       [ 479.        ,  566.5       ,  442.5       ,  566.5       ,
         486.77777778],
       ...,
       [2580.        , 2580.        , 1450.        , 1450.        ,
        2168.55555556],
       [1117.5       , 1117.5       ,  777.5       ,  778.5       ,
         884.05555556],
       [ 459.5       ,  951.5       ,  459.5       ,  951.5       ,
         669.5       ]])

E0916 20:00:25.108439 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


33

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 225.5       ,  294.        ,  219.5       ,  294.        ,
         244.88888889],
       [ 393.5       ,  535.5       ,  393.5       ,  535.5       ,
         475.88888889],
       [ 479.        ,  566.5       ,  442.5       ,  566.5       ,
         486.77777778],
       ...,
       [2580.        , 2580.        , 1450.        , 1450.        ,
        2168.55555556],
       [1117.5       , 1117.5       ,  777.5       ,  778.5       ,
         884.05555556],
       [ 459.5       ,  951.5       ,  459.5       ,  951.5       ,
         669.5       ]])

E0916 20:00:25.145490 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


34

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 225.5       ,  294.        ,  219.5       ,  294.        ,
         244.88888889],
       [ 393.5       ,  535.5       ,  393.5       ,  535.5       ,
         475.88888889],
       [ 479.        ,  566.5       ,  442.5       ,  566.5       ,
         486.77777778],
       ...,
       [2580.        , 2580.        , 1450.        , 1450.        ,
        2168.55555556],
       [1117.5       , 1117.5       ,  777.5       ,  778.5       ,
         884.05555556],
       [ 459.5       ,  951.5       ,  459.5       ,  951.5       ,
         669.5       ]])

E0916 20:00:25.181784 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


35

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 225.5       ,  294.        ,  219.5       ,  294.        ,
         244.88888889],
       [ 393.5       ,  535.5       ,  393.5       ,  535.5       ,
         475.88888889],
       [ 479.        ,  566.5       ,  442.5       ,  566.5       ,
         486.77777778],
       ...,
       [2580.        , 2580.        , 1450.        , 1450.        ,
        2168.55555556],
       [1117.5       , 1117.5       ,  777.5       ,  778.5       ,
         884.05555556],
       [ 459.5       ,  951.5       ,  459.5       ,  951.5       ,
         669.5       ]])

E0916 20:00:25.215501 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


36

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 716.1       , 1529.6       ,  714.6       , 1529.6       ,
        1003.46666667],
       [ 817.3       , 1356.        ,  817.3       , 1356.        ,
        1085.41111111],
       [1404.8       , 1530.5       , 1383.1       , 1498.        ,
        1448.17777778],
       ...,
       [2457.5       , 2612.5       , 1946.1       , 1946.1       ,
        2283.72222222],
       [2066.7       , 2379.2       , 1844.1       , 2379.2       ,
        2172.45555556],
       [ 853.3       , 1736.2       ,  853.3       , 1736.2       ,
        1349.5       ]])

E0916 20:00:25.250930 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


37

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 716.1       , 1529.6       ,  714.6       , 1529.6       ,
        1003.46666667],
       [ 817.3       , 1356.        ,  817.3       , 1356.        ,
        1085.41111111],
       [1404.8       , 1530.5       , 1383.1       , 1498.        ,
        1448.17777778],
       ...,
       [2457.5       , 2612.5       , 1946.1       , 1946.1       ,
        2283.72222222],
       [2066.7       , 2379.2       , 1844.1       , 2379.2       ,
        2172.45555556],
       [ 853.3       , 1736.2       ,  853.3       , 1736.2       ,
        1349.5       ]])

E0916 20:00:25.283755 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


38

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 716.1       , 1529.6       ,  714.6       , 1529.6       ,
        1003.46666667],
       [ 817.3       , 1356.        ,  817.3       , 1356.        ,
        1085.41111111],
       [1404.8       , 1530.5       , 1383.1       , 1498.        ,
        1448.17777778],
       ...,
       [2457.5       , 2612.5       , 1946.1       , 1946.1       ,
        2283.72222222],
       [2066.7       , 2379.2       , 1844.1       , 2379.2       ,
        2172.45555556],
       [ 853.3       , 1736.2       ,  853.3       , 1736.2       ,
        1349.5       ]])

E0916 20:00:25.316282 139779581159232 common_util.py:2089] CRITICAL - time to load data: now


39

'f.shape: (1358, 5), l.shape:(1358,), t.shape:(1358,)'

'f:'

array([[ 716.1       , 1529.6       ,  714.6       , 1529.6       ,
        1003.46666667],
       [ 817.3       , 1356.        ,  817.3       , 1356.        ,
        1085.41111111],
       [1404.8       , 1530.5       , 1383.1       , 1498.        ,
        1448.17777778],
       ...,
       [2457.5       , 2612.5       , 1946.1       , 1946.1       ,
        2283.72222222],
       [2066.7       , 2379.2       , 1844.1       , 2379.2       ,
        2172.45555556],
       [ 853.3       , 1736.2       ,  853.3       , 1736.2       ,
        1349.5       ]])